### PR TITLE
Added webflight in the module section.

### PR DESCRIPTION
**Pull request by eschnou**
Re-submitting this change, I didn't realized the website had changed.

### CODE REVIEW

**Comment by tim-kos** [comment]
Thank you!

**Comment by felixge** [comment]
What's up with the diff on this? Did you change spaces or something?

**Comment by eschnou** [comment]
@felixge lol good catch :-) I did the edit via the Github UI and just added ONE line, everything else happened automagically... No clue what went wrong. Maybe there were trailing whitespaces? Anyway, next time I'll do a good old fork + pull-request.

**Comment by felixge** [comment]
Alright, I'll trust you that you didn't sneak a backdoor into things :trollface:

**Comment by eschnou** [comment]
@felixge You are an emoticons master :-)

**Comment by tim-kos** [comment]
I checked the diff before I merged it. There was really only one different,
so must have been spaces. I merged it anyway, so. :P

On Fri, May 31, 2013 at 3:00 PM, Laurent Eschenauer <
notifications@github.com> wrote:

> @felixge https://github.com/felixge You are an emoticons master :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodecopter/nodecopter.com/pull/25#issuecomment-18764997
> .

## 

Practicing and Teaching the Art of Web Engineering

Tim Koschützki
Director
www.debuggable.com

Debuggable Limited
Friedrichstr. 171
Einstein Palais
10117 Berlin
Mob: +49 (151) 19161166

Commercial Register:  HRB 112594 B  (Charlottenburg, Berlin)
Directors: Tim Koschützki, Felix Geisendörfer
VAT-ID: DE263164617

**Pull request merged**
