### PR TITLE
Add ticket link to brighton event

### PR DESCRIPTION
**Pull request by remy**
As per subject

### CODE REVIEW

**Comment by felixge** [comment]
Restored your access. But rejecting this one. The event page should stay on the nodecopter page.

I'm reworking the homepage now and will link to the brighton sub-page.

**Comment by felixge** [comment]
Oh wait, I misread. I thought you were doing a link on the homepage. And I misread where the link is going as well.

Sorry, merging!

**Comment by remy** [comment]
Ha - yeah, don't worry, I was staying in my box :)

**Comment by felixge** [comment]
:+1: - well, we're just trying to put some structure in place. If everybody is going to use their own stuff it's going to be insane chaos for us trying to help : )

**Comment by remy** [comment]
I'll need to send another pull request to get the current sponsors on that
page too - but I'm still gathering the logos.

Basically I've just sent out a request to local companies to support the
event, but pointed them to the nodecopter brighton page instead of the tito
page - so it would be great to get a deploy soon too!

On 25 October 2012 11:29, Felix Geisendörfer notifications@github.comwrote:

> [image: :+1:] - well, we're just trying to put some structure in place.
> If everybody is going to use their own stuff it's going to be insane chaos
> for us trying to help : )
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodecopter/nodecopter.com/pull/2#issuecomment-9772719.

## 

I'm running a developer toolkit workshop - a choice of 6 topics,
run by 3 teachers, 1 day - £220:
https://leftlogic.stagehq.com/events/1518

---

email & IM ~ remy@leftlogic.com
twitter ~ @rem
web ~ http://leftlogic.com
blog ~ http://remysharp.com

mob ~ +44 (0) 7590 497 258
tel ~ +44 (0) 1273 557744
fax ~ +44 (0) 1273 806580

Left Logic Ltd. Registered in England and Wales (registered no. 05926047).
Registered Office: 44 Burstead Close, Brighton, BN1 7HT, United Kingdom.
VAT registration: 993 1266 95

**Comment by felixge** [comment]
@remy I restored your access, so you should be able to deploy with `rm -rf build; romulus deploy` at any time.

**Comment by felixge** [comment]
(sorry about the `rm -rf` thing, I'm hacking on romulus as fast as I can, but it's not done yet)

**Comment by felixge** [comment]
(Also make sure you update to the latest romulus)

**Comment by remy** [comment]
Cool - no problem.  I've just deployed and that worked.

Cheers,
- Remy

**Comment by felixge** [comment]
> Cool - no problem.  I've just deployed and that worked.

I think you deployed using an old version of romulus, it broke some pages. Please always update.

**Comment by remy** [comment]
Yeah, I deployed before I got your email about updating :-\

Sorry!

<< rem will always update >>

Do you need me to do re-deploy or is it okay now?

**Comment by felixge** [comment]
> Do you need me to do re-deploy or is it okay now?

No, all good now.

Sorry for writing using my own half-done thingie for the site, but I wanted something written in node and I didn't like some of the design decisions in jekyll ... so I re-invented the wheel : ).

**Pull request merged**
