### PR TITLE
List nodecopter modules from npm

### PR DESCRIPTION
**Pull request by shama**
This will list modules from npm with the keyword `nodecopter` on the /modules page. It will put the results into localStorage, if available, and use that on subsequent visits.

Currently there are only two modules published with the keyword `nodecopter`. Hopefully this will encourage more authors to do so and this list later could be fully generated from npm.

A good example of this is on http://gruntjs.com

Thanks!

### CODE REVIEW

**Comment by csanz** [comment]
Great idea!

**Comment by felixge** [comment]
@shama : Great idea. I just made you a contributor on this repo (and some others), so you can push this patch yourself once you're happy with it.

IMO it's a great patch, but a few things could be improved:
- Use 2 space indention (your `modules.js` file uses a mix of tabs and spaces)
- Is it possible to perform a free-text search? Like `npm search` itself does? This finds 4 rather than 2 modules for me.

Anyway, thank you so much for you help! :heart:

**Comment by shama** [comment]
Oh awesome, thank you Felix! I fixed the indentation and will look into the free-text search.

BTW, I had a blast at the dronegames today. Thanks for hosting @csanz!

**Comment by shama** [comment]
Phew, I learned more about CouchDB than I intended. There is not a free-text search for npm. @isaacs said someone was working on integrating elastic search though.

This PR will now search npm 1000 rows at a time for `nodecopter` within the `name` or `description` and search for modules with the keyword `nodecopter`. Then will store results into local storage. Similar to how `npm search` does it. Currently this yields 5 modules.

So hopefully this way is cool and there are no objections. Then I'll merge this in. Thank you!

**Comment by shama** [comment]
Merged on 4635ea6c62353ce8268a9e4fc1b4be7700e94ff7. Thanks!

**Pull request closed without merging**
